In [1]:
from pycaret.datasets import get_data

data = get_data("iris")
data.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [2]:
from pycaret.classification import *

setup(data=data, target="species", session_id=123)

best = compare_models()

predict_model(best)

,sepal_length,sepal_width,petal_length,petal_width,species,prediction_label,prediction_score
72,6.3,2.5,4.9,1.5,Iris-versicolor,Iris-versicolor,0.5203
125,7.2,3.2,6.0,1.8,Iris-virginica,Iris-virginica,0.9503
80,5.5,2.4,3.8,1.1,Iris-versicolor,Iris-versicolor,0.9334
86,6.7,3.1,4.7,1.5,Iris-versicolor,Iris-versicolor,0.7320
117,7.7,3.8,6.7,2.2,Iris-virginica,Iris-virginica,0.9953
17,5.1,3.5,1.4,0.3,Iris-setosa,Iris-setosa,0.9770
33,5.5,4.2,1.4,0.2,Iris-setosa,Iris-setosa,0.9850
68,6.2,2.2,4.5,1.5,Iris-versicolor,Iris-versicolor,0.7216
2,4.7,3.2,1.3,0.2,Iris-setosa,Iris-setosa,0.9820
28,5.2,3.4,1.4,0.2,Iris-setosa,Iris-setosa,0.9729
122,7.7,2.8,6.7,2.0,Iris-virginica,Iris-virginica,0.9952
19,5.1,3.8,1.5,0.3,Iris-setosa,Iris-setosa,0.9793
116,6.5,3.0,5.5,1.8,Iris-virginica,Iris-virginica,0.8739
22,4.6,3.6,1.0,0.2,Iris-setosa,Iris-setosa,0.9942
91,6.1,3.0,4.6,1.4,Iris-versicolor,Iris-versicolor,0.7809
9,4.9,3.1,1.5,0.1,Iris-setosa,Iris-setosa,0.9650
146,6.3,2.5,5.0,1.9,Iris-virginica,Iris-virginica,0.7621
101,5.8,2.7,5.1,1.9,Iris-virginica,Iris-virginica,0.8141
38,4.4,3.0,1.3,0.2,Iris-setosa,Iris-setosa,0.9826
39,5.1,3.4,1.5,0.2,Iris-setosa,Iris-setosa,0.9692
37,4.9,3.1,1.5,0.1,Iris-setosa,Iris-setosa,0.9650
42,4.4,3.2,1.3,0.2,Iris-setosa,Iris-setosa,0.9859
25,5.0,3.0,1.6,0.2,Iris-setosa,Iris-setosa,0.9474
65,6.7,3.1,4.4,1.4,Iris-versicolor,Iris-versicolor,0.8792
32,5.2,4.1,1.5,0.1,Iris-setosa,Iris-setosa,0.9842
56,6.3,3.3,4.7,1.6,Iris-versicolor,Iris-versicolor,0.6756
115,6.4,3.2,5.3,2.3,Iris-virginica,Iris-virginica,0.9291
34,4.9,3.1,1.5,0.1,Iris-setosa,Iris-setosa,0.9650
76,6.8,2.8,4.8,1.4,Iris-versicolor,Iris-versicolor,0.7066
143,6.8,3.2,5.9,2.3,Iris-virginica,Iris-virginica,0.9827
144,6.7,3.3,5.7,2.5,Iris-virginica,Iris-virginica,0.9817
100,6.3,3.3,6.0,2.5,Iris-virginica,Iris-virginica,0.9926
138,6.0,3.0,4.8,1.8,Iris-virginica,Iris-virginica,0.5580
57,4.9,2.4,3.3,1.0,Iris-versicolor,Iris-versicolor,0.8105
93,5.0,2.3,3.3,1.0,Iris-versicolor,Iris-versicolor,0.8371
61,5.9,3.0,4.2,1.5,Iris-versicolor,Iris-versicolor,0.8673
127,6.1,3.0,4.9,1.8,Iris-virginica,Iris-virginica,0.6151
77,6.7,3.0,5.0,1.7,Iris-versicolor,Iris-virginica,0.5773
110,6.5,3.2,5.1,2.0,Iris-virginica,Iris-virginica,0.7819
45,4.8,3.0,1.4,0.3,Iris-setosa,Iris-setosa,0.9697
135,7.7,3.0,6.1,2.3,Iris-virginica,Iris-virginica,0.9878
64,5.6,2.9,3.6,1.3,Iris-versicolor,Iris-versicolor,0.8886
66,5.6,3.0,4.5,1.5,Iris-versicolor,Iris-versicolor,0.7543
105,7.6,3.0,6.6,2.1,Iris-virginica,Iris-virginica,0.9948
63,6.1,2.9,4.7,1.4,Iris-versicolor,Iris-versicolor,0.7260